Update README.md
github/renaming pull request #17
Opened 2022-03-18 00:40 UTC by korewa456

2022-04-04 18:23 UTC, cassidyjames requested changes
Looks like spam or a typo?

2022-04-11 08:56 UTC, AdNaN-rK requested changes
Request changes

2022-04-11 09:10 UTC, AdNaN-rK requested changes

2022-04-11 09:10 UTC, AdNaN-rK commented on README.md
Ch

2022-06-03 09:21 UTC, Bishem commented
a ok

2022-09-24 14:45 UTC, jaypalmandloi approved these changes

2022-10-27 13:17 UTC, ssbarnea requested changes
Someone please close this PR

2023-04-14 12:42 UTC, henish1400 commented
ss

2023-04-18 10:05 UTC, ELHoussineT commented
Close this.

2023-04-19 16:17 UTC, adarshank33 commented on README.md
> +- [We've updated GitHub.com](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/) to redirect links that contain the deleted brancfenew default bran
hiii

2023-04-19 19:53 UTC, KaspianDev commented
:trollface:

2023-04-19 20:58 UTC, closed without merging